# Generated by Django 5.1.5 on 2025-05-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FEEDBACK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(choices=[('', ''), ('Complaint', 'complaint'), ('Feedback', 'feedback')], default='')),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('password', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MANAGER',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('password', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='POLICIES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policies', models.TextField()),
                ('enacted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.TextField(default='')),
                ('status', models.TextField(choices=[('Married', 'married'), ('Single', 'single')])),
                ('gender', models.TextField(choices=[('Male', 'male'), ('Female', 'female')])),
                ('date_of_birth', models.DateField()),
                ('bank_number', models.TextField()),
                ('emergency_contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RECRUITMENT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.TextField(default='')),
                ('reason', models.TextField(default='')),
                ('total_personnel', models.IntegerField(default=0)),
                ('managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.manager')),
            ],
        ),
        migrations.CreateModel(
            name='PAYROLL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pcb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('epf_employer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('epf_employee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LEAVE_BALANCE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annual_leave', models.IntegerField(default=14)),
                ('leave_available', models.IntegerField(default=14)),
                ('year', models.IntegerField(default=2025)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('staffid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='HRMS.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EXPERIENCE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EDUCATON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certification', models.TextField()),
                ('date_received', models.DateField()),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.TextField(default='')),
                ('address2', models.TextField(default='')),
                ('poscode', models.IntegerField(default='')),
                ('state', models.TextField(default='')),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TEAM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('goals', models.TextField()),
                ('managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.manager')),
            ],
        ),
        migrations.CreateModel(
            name='TIMEOFF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.TextField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Denied', 'denied')], default='Pending')),
                ('reason', models.TextField()),
                ('total_days', models.IntegerField(default=0)),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TEAM_MEMBERSHIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='HRMS.team')),
            ],
            options={
                'unique_together': {('team', 'staff')},
            },
        ),
    ]
