# Generated by Django 5.1.5 on 2025-05-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0002_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EDUCATON',
            new_name='EDUCATION',
        ),
    ]
