# Generated by Django 5.1.5 on 2025-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0003_rename_educaton_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bank_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.TextField(choices=[('', ''), ('Male', 'male'), ('Female', 'female')], default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.TextField(choices=[('', ''), ('Married', 'married'), ('Single', 'single')], default=''),
        ),
    ]
