# Generated by Django 5.1.5 on 2025-05-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0004_alter_staff_bank_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='staffid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff'),
        ),
        migrations.AddField(
            model_name='manager',
            name='staffid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HRMS.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='name',
            field=models.TextField(),
        ),
    ]
