# Generated by Django 5.1.5 on 2025-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0005_hr_staffid_manager_staffid_alter_hr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='goals',
            field=models.TextField(default=''),
        ),
    ]
