# Generated by Django 5.1.5 on 2025-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0006_alter_team_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.TextField(default=''),
        ),
    ]
