# Generated by Django 5.1.5 on 2025-05-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0007_staff_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
    ]
