# Generated by Django 5.1.5 on 2025-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0008_remove_hr_name_remove_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.TextField(choices=[('Unsolved', 'unsolved'), ('Solved', 'solved')], default='Unsolved'),
        ),
    ]
