# Generated by Django 5.1.5 on 2025-05-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0010_remove_team_goals_team_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ['-requested_date'], 'verbose_name': 'Recruitment Request', 'verbose_name_plural': 'Recruitment Requests'},
        ),
        migrations.AddField(
            model_name='recruitment',
            name='assigned_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRMS.hr'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='business_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='department',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='employment_type',
            field=models.TextField(choices=[('Full-time', 'full_time'), ('Part-time', 'part_time'), ('Contract', 'contract'), ('Temporary', 'temporary'), ('Internship', 'internship')], default='Full-time'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='expected_timeline',
            field=models.TextField(choices=[('1-2 weeks', '1-2 weeks'), ('2-4 weeks', '2-4 weeks'), ('1-2 months', '1-2 months'), ('2-3 months', '2-3 months'), ('3+ months', '3+ months')], default='2-4 weeks'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='external_posting_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='justification_type',
            field=models.TextField(choices=[('New Position', 'new_position'), ('Replacement', 'replacement'), ('Expansion', 'expansion'), ('Temporary Cover', 'temporary_cover'), ('Project Based', 'project_based')], default='New Position'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='preferred_qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='priority',
            field=models.TextField(choices=[('Low', 'low'), ('Standard', 'standard'), ('High', 'high'), ('Urgent', 'urgent'), ('Critical', 'critical')], default='Standard'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='remote_work_option',
            field=models.TextField(choices=[('On-site', 'on_site'), ('Remote', 'remote'), ('Hybrid', 'hybrid')], default='On-site'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='required_qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='salary_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='salary_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='status',
            field=models.TextField(choices=[('Pending', 'pending'), ('Under Review', 'under_review'), ('Approved', 'approved'), ('In Progress', 'in_progress'), ('Completed', 'completed'), ('Rejected', 'rejected'), ('On Hold', 'on_hold'), ('More Info Needed', 'more_info_needed')], default='Pending'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='target_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_updates', to='HRMS.hr'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='work_location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='total_personnel',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RECRUITMENT_ATTACHMENTS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to='recruitment_attachments/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('attachment_type', models.TextField(choices=[('Job Description', 'job_description'), ('Budget Approval', 'budget_approval'), ('Organizational Chart', 'org_chart'), ('Supporting Document', 'supporting_doc'), ('Other', 'other')], default='Other')),
                ('description', models.TextField(blank=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='HRMS.recruitment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.hr')),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='RECRUITMENT_NOTES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_type', models.TextField(choices=[('HR Internal', 'hr_internal'), ('Manager Feedback', 'manager_feedback'), ('Status Update', 'status_update'), ('Interview Note', 'interview_note'), ('General', 'general')], default='General')),
                ('note_content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_manager', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.hr')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='HRMS.recruitment')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RECRUITMENT_STATUS_HISTORY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_status', models.TextField(blank=True)),
                ('new_status', models.TextField()),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.hr')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='HRMS.recruitment')),
            ],
            options={
                'ordering': ['-changed_date'],
            },
        ),
    ]
