# Generated by Django 5.1.5 on 2025-06-09 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0011_alter_recruitment_options_recruitment_assigned_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_attachments',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='HRMS.recruitment'),
        ),
        migrations.AlterField(
            model_name='recruitment_attachments',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRMS.hr'),
        ),
        migrations.AlterField(
            model_name='recruitment_notes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRMS.hr'),
        ),
        migrations.AlterField(
            model_name='recruitment_notes',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='HRMS.recruitment'),
        ),
        migrations.AlterField(
            model_name='recruitment_status_history',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRMS.hr'),
        ),
        migrations.AlterField(
            model_name='recruitment_status_history',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='HRMS.recruitment'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='staffid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRMS.staff'),
        ),
    ]
