# Generated by Django 5.1.5 on 2025-06-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0012_alter_recruitment_attachments_recruitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='budget_allocated',
        ),
    ]
